service: home

image: schrockwell/home

servers:
  web:
    - kamal.schrockwell.com

proxy:
  ssl: true
  ssl_redirect: false # allow HTTP
  hosts:
    - home.schrockwell.com
    - schrockwell.com
    - www.schrockwell.com
  app_port: 3000
  healthcheck:
    path: /

registry:
  server: localhost:5555

builder:
  arch: amd64
  remote: ssh://root@kamal.schrockwell.com